- hosts: server
  tasks:

# scp install scripts
  - name: scp install_scripts
    copy: src=~/git/server-setup/install_scripts/install_perl.ksh dest={{proot}}/src/install_scripts/install_perl.ksh owner=ucomm group=ucomm mode=0644

# perl-5.22.0 
  - name: scp perl-5.22.0.tar.gz
    copy: src=~/git/server-setup/download/perl-5.22.0.tar.gz dest={{proot}}/src/download owner=ucomm group=ucomm mode=0644

  - name: install_perl
    shell:  source ~/.kshrc; ksh {{proot}}/src/install_scripts/install_perl.ksh
    notify:
    - log 

