- hosts: server
  tasks:

# scp install scripts
  - name: scp install_scripts
    copy: src=~/git/server-setup/install_scripts/install_git.ksh dest={{proot}}/src/install_scripts/install_git.ksh owner=ucomm group=ucomm mode=0644

# git-2.4.9
  - name: scp git-2.4.9.tar.gz
    copy: src=~/git/server-setup/download/git-2.4.9.tar.gz dest={{proot}}/src/download owner=ucomm group=ucomm mode=0644

  - name: install_git
    shell:  source ~/.kshrc; ksh {{proot}}/src/install_scripts/install_git.ksh
    notify:
    - log 

