- hosts: server
  tasks:

# scp install scripts
  - name: scp install_scripts
    copy: src=~/git/server-setup/install_scripts/install_zlib.ksh dest={{proot}}/src/install_scripts/install_zlib.ksh owner=ucomm group=ucomm mode=0644

# zlib-1.2.8
  - name: scp zlib-1.2.8.tar.gz
    copy: src=~/git/server-setup/download/zlib-1.2.8.tar.gz dest={{proot}}/src/download owner=ucomm group=ucomm mode=0644

  - name: install_zlib
    shell:  source ~/.kshrc; ksh {{proot}}/src/install_scripts/install_zlib.ksh
    notify:
    - log 

