- hosts: server
  tasks:

# scp install scripts
  - name: scp install_scripts
    copy: src=~/git/server-setup/install_scripts/install_libmemcached.ksh dest={{proot}}/src/install_scripts/install_libmemcached.ksh owner=ucomm group=ucomm mode=0644

# libmemcached-1.0.18
  - name: scp libmemcached-1.0.18.tar.gz
    copy: src=~/git/server-setup/download/libmemcached-1.0.18.tar.gz dest={{proot}}/src/download owner=ucomm group=ucomm mode=0644

  - name: install_libmemcached
    shell:  source ~/.kshrc; ksh {{proot}}/src/install_scripts/install_libmemcached.ksh
    notify:
    - log 

