- hosts: server
  tasks:

# scp install scripts
  - name: scp install_scripts
    copy: src=~/git/server-setup/install_scripts/install_phpmemcached.ksh dest={{proot}}/src/install_scripts/install_phpmemcached.ksh owner=ucomm group=ucomm mode=0644

# memcached-2.2.0
  - name: scp memcached-2.2.0.tgz
    copy: src=~/git/server-setup/download/memcached-2.2.0.tgz dest={{proot}}/src/download owner=ucomm group=ucomm mode=0644

  - name: install_phpmemcached
    shell:  source ~/.kshrc; ksh {{proot}}/src/install_scripts/install_phpmemcached.ksh
    notify:
    - log 

