- hosts: server
  tasks:

# scp install scripts
  - name: scp install_scripts
    copy: src=~/git/server-setup/install_scripts/install_openssl.ksh dest={{proot}}/src/install_scripts/install_openssl.ksh owner=ucomm group=ucomm mode=0644

# openssl-1.0.2g
  - name: scp openssl-1.0.2g.tar.gz
    copy: src=~/git/server-setup/download/openssl-1.0.2g.tar.gz dest={{proot}}/src/download owner=ucomm group=ucomm mode=0644

  - name: install_openssl
    shell:  source ~/.kshrc; ksh {{proot}}/src/install_scripts/install_openssl.ksh
    notify:
    - log 

